// Catálogo Kasa Diamante — datos de productos
// Precios en COP (pesos colombianos)

export const KD_CATEGORIES = [
  { id: 'comedores',   label: 'Comedores',          short: 'Comedor' },
  { id: 'sofas',       label: 'Sofás y sillones',   short: 'Sofá' },
  { id: 'mesas',       label: 'Mesas',              short: 'Mesa' },
  { id: 'lamparas',    label: 'Lámparas',           short: 'Lámpara' },
  { id: 'camas',       label: 'Camas y recámara',   short: 'Cama' },
  { id: 'sillas',      label: 'Sillas',             short: 'Silla' },
  { id: 'espejos',     label: 'Espejos',            short: 'Espejo' },
  { id: 'decoracion',  label: 'Decoración',         short: 'Decoración' },
  { id: 'alfombras',   label: 'Alfombras',          short: 'Alfombra' },
];

export const fmtCOP = (n) => '$ ' + n.toLocaleString('es-CO');

export const KD_PRODUCTS = [
  // ── Comedores ──
  {
    id: 'c-versalles',  cat: 'comedores', name: 'Versalles', coll: 'Atelier Noir',
    price: 18900000, w: 240, seats: 8, material: 'Roble macizo · herrajes en latón', year: 2025,
    spec: {
      desc: 'Mesa de comedor monumental tallada en roble macizo americano seleccionado a mano. La superficie presenta un veteado natural irrepetible, tratada con aceites de teka que realzan la profundidad de la madera. Los herrajes en latón envejecido —anillas, uniones y cantos— son forjados individualmente en el taller aliado de Medellín. Cada pieza está numerada y firmada por el maestro artesano.',
      dims: { largo: 240, ancho: 105, alto: 76 },
      finish: 'Roble con aceite de teka natural · Herrajes latón envejecido a mano',
      care: 'Limpiar con paño seco suave. Evitar exposición directa a la humedad. Reacondicionar anualmente con aceite de teka o cera de carnauba.',
      origin: 'Taller Cortés & Asociados · Medellín, Colombia',
      delivery: '5 a 7 semanas',
      stock: 2,
    },
  },
  {
    id: 'c-monaco',     cat: 'comedores', name: 'Mónaco', coll: 'Maison Doré',
    price: 14500000, w: 220, seats: 8, material: 'Mármol Calacatta · base lacada', year: 2025,
    spec: {
      desc: 'Tablero en mármol Calacatta italiano con veteado dorado único, cortado en slab completo para garantizar la continuidad visual. La base estructural está lacada en negro piano con acabado de alto brillo. Una pieza de contraste dramático que domina cualquier comedor con presencia escultórica.',
      dims: { largo: 220, ancho: 100, alto: 75 },
      finish: 'Mármol Calacatta pulido · Base lacada negro piano',
      care: 'Mármol: limpiar con paño húmedo y jabón neutro. Evitar ácidos y abrasivos. Aplicar sellador de mármol cada 12 meses.',
      origin: 'Taller Mármoles del Valle · Bogotá · Piedra importada de Carrara, Italia',
      delivery: '6 a 8 semanas',
      stock: 1,
    },
  },
  {
    id: 'c-belgrave',   cat: 'comedores', name: 'Belgrave', coll: 'Atelier Noir',
    price: 12200000, w: 200, seats: 6, material: 'Nogal americano · acabado mate', year: 2024,
    spec: {
      desc: 'Mesa de comedor en nogal americano macizo con acabado mate que suaviza la veta sin opacarla. El diseño de líneas limpias y patas en ligero ángulo le da movimiento estructural sin sacrificar la solidez. Una pieza diseñada para durar generaciones.',
      dims: { largo: 200, ancho: 95, alto: 75 },
      finish: 'Nogal americano con barniz mate al agua · Sin herrajes visibles',
      care: 'Limpiar con paño seco. Para manchas, paño levemente húmedo con jabón neutro. No exponer a luz solar directa prolongada.',
      origin: 'Taller Maderas Nobles · Cali, Colombia',
      delivery: '4 a 6 semanas',
      stock: 3,
    },
  },
  {
    id: 'c-saint',      cat: 'comedores', name: 'Saint-Honoré', coll: 'Maison Doré',
    price: 21500000, w: 260, seats: 10, material: 'Ónix · pedestal escultórico', year: 2025,
    spec: {
      desc: 'La pieza más imponente de Maison Doré: un tablero en ónix translúcido retroiluminado desde el interior por LEDs de temperatura cálida, montado sobre un pedestal escultórico en acero inoxidable con baño en oro. En la oscuridad, la mesa se convierte en una fuente de luz propia. Producción de solo 4 unidades anuales.',
      dims: { largo: 260, ancho: 110, alto: 76 },
      finish: 'Ónix miel translúcido pulido · Pedestal acero con baño en oro 24K · LEDs 2700K integrados',
      care: 'Ónix: solo paño seco o ligeramente húmedo. Jamás ácidos. Pedestal: paño suave seco. Sistema LED garantía 5 años, consumo 18W.',
      origin: 'Taller Piedra & Luz · Ciudad de México · Ónix de cantera Querétaro',
      delivery: '10 a 14 semanas',
      stock: 1,
    },
  },
  {
    id: 'c-toscana',    cat: 'comedores', name: 'Toscana', coll: 'Casa Mediterránea',
    price: 9800000, w: 180, seats: 6, material: 'Travertino romano', year: 2024,
    spec: {
      desc: 'Mesa de comedor en travertino romano de cantera italiana, con su característica textura porosa natural y tonos tierra. El tablero de 4 cm de grosor es soportado por cuatro patas cilíndricas del mismo material, creando una coherencia visual de bloque monolítico. Perfecta para comedores con luz natural abundante.',
      dims: { largo: 180, ancho: 90, alto: 74 },
      finish: 'Travertino romano pulido en cara superior · Lados y patas en acabado rústico',
      care: 'Sellar anualmente con sellador para piedra calcárea. Limpiar con agua y jabón neutro. No dejar líquidos sobre la superficie por tiempo prolongado.',
      origin: 'Canteras Borghese · Roma, Italia · Montaje en taller Bogotá',
      delivery: '8 a 10 semanas',
      stock: 2,
    },
  },
  {
    id: 'c-orient',     cat: 'comedores', name: 'Orient', coll: 'Atelier Noir',
    price: 16700000, w: 220, seats: 8, material: 'Ébano · incrustaciones latón', year: 2025,
    spec: {
      desc: 'Mesa de comedor en ébano macacasar —una de las maderas más densas y valiosas del mundo— con incrustaciones geométricas de latón forjado a mano que trazan líneas de luz sobre la oscuridad de la madera. Un trabajo de marquetería contemporánea que honra tradiciones artesanales centenarias.',
      dims: { largo: 220, ancho: 100, alto: 76 },
      finish: 'Ébano macacasar lacado mate · Incrustaciones latón pulido sin protección',
      care: 'Paño seco de microfibra. Aplicar aceite de linaza refinado cada 18 meses. Las incrustaciones de latón pueden pulirse con paño suave seco.',
      origin: 'Taller Herencia Artesanal · Cartagena, Colombia',
      delivery: '8 a 12 semanas',
      stock: 1,
    },
  },

  // ── Sofás ──
  {
    id: 'sf-coco',      cat: 'sofas', name: 'Coco', coll: 'Maison Doré',
    price: 13800000, w: 280, material: 'Bouclé crema · estructura roble', year: 2025,
    spec: {
      desc: 'Sofá de tres cuerpos con tapizado en bouclé crema de alta densidad, una tela de hilo rizado que aporta textura visual y tactilidad inmediata. La estructura de roble macizo es visible en patas y apoyabrazos, creando un diálogo cálido entre madera y textil. Asientos con plumas de pato envueltas en espuma HR de alta resiliencia.',
      dims: { largo: 280, profundo: 95, alto: 82, alt_asiento: 42 },
      finish: 'Bouclé crema marfil · Roble natural oil finish',
      care: 'Aspirar regularmente. Manchas puntuales: paño húmedo con jabón neutro. No exponer a luz solar directa. Remover cojines y airear semanalmente.',
      origin: 'Taller Tapicería Fina · Bogotá, Colombia · Tela importada de Bélgica',
      delivery: '6 a 8 semanas',
      stock: 4,
    },
  },
  {
    id: 'sf-modena',    cat: 'sofas', name: 'Modena', coll: 'Atelier Noir',
    price: 16200000, w: 320, material: 'Cuero italiano cognac', year: 2025,
    spec: {
      desc: 'Sofá de cuatro módulos tapizado en cuero italiano full-aniline en tono cognac, el grano más fino disponible en cuero plena flor. El curtido natural permite que el cuero desarrolle una pátina única con el tiempo. Estructura en madera de haya, patas en acero satinado. Respaldo de ángulo relajado para largas conversaciones.',
      dims: { largo: 320, profundo: 100, alto: 78, alt_asiento: 44 },
      finish: 'Cuero full-aniline cognac · Patas acero satinado',
      care: 'Limpiar con crema hidratante específica para cuero plena flor cada 3 meses. Manchas: paño seco de inmediato. No usar detergentes ni agua en exceso.',
      origin: 'Poltrona Frau · Tolentino, Italia · Montaje final en Bogotá',
      delivery: '10 a 14 semanas',
      stock: 2,
    },
  },
  {
    id: 'sf-savoy',     cat: 'sofas', name: 'Savoy', coll: 'Maison Doré',
    price: 11400000, w: 240, material: 'Terciopelo verde profundo', year: 2024,
    spec: {
      desc: 'Sofá de dos plazas con estilo Chesterfield contemporáneo en terciopelo verde esmeralda de pelo corto. El acolchado capitoné en respaldo y brazos mantiene la elegancia clásica, mientras que las patas doradas aportan el acento de lujo. Una pieza que funciona como joya de sala.',
      dims: { largo: 240, profundo: 88, alto: 84, alt_asiento: 44 },
      finish: 'Terciopelo verde esmeralda · Patas lacadas en oro pulido',
      care: 'Cepillar en el sentido del pelo suavemente. Aspirar a baja potencia. Manchas: paño levemente húmedo y secado inmediato.',
      origin: 'Taller Tapicería Clásica · Bogotá, Colombia · Terciopelo importado de Francia',
      delivery: '5 a 7 semanas',
      stock: 3,
    },
  },
  {
    id: 'sf-ginza',     cat: 'sofas', name: 'Ginza', coll: 'Casa Mediterránea',
    price: 9700000, w: 220, material: 'Lino belga arena', year: 2024,
    spec: {
      desc: 'Sofá de dos módulos en lino belga arena natural, la tela más respirable y naturalmente antiestática. La estructura de madera es completamente invisible, y los cojines —en espuma de alta densidad envuelta en fibra de poliéster— mantienen su forma sin necesidad de recolocarlos constantemente.',
      dims: { largo: 220, profundo: 92, alto: 75, alt_asiento: 40 },
      finish: 'Lino belga arena natural · Costuras expuestas en hilo crudo',
      care: 'Fundas de cojines removibles y lavables en frío. El tapizado fijo se limpia con paño húmedo y jabón neutro. Airear frecuentemente.',
      origin: 'Taller Habitat · Medellín, Colombia · Lino importado de Bélgica',
      delivery: '4 a 6 semanas',
      stock: 5,
    },
  },
  {
    id: 'sf-noir',      cat: 'sofas', name: 'Noir', coll: 'Atelier Noir',
    price: 18900000, w: 340, material: 'Mohair grafito · pies latón', year: 2025,
    spec: {
      desc: 'Sofá de cuatro módulos en mohair grafito oscuro, la tela más lujosa en tapicería: fibra natural de cabra de angora con brillo metálico sutil. Las patas torneadas en latón macizo están posicionadas en los ocho extremos visibles del conjunto. Una pieza que exige todo el espacio y la atención de la sala.',
      dims: { largo: 340, profundo: 102, alto: 80, alt_asiento: 43 },
      finish: 'Mohair grafito oscuro · Patas latón macizo torneado',
      care: 'Cepillar suavemente en sentido del pelo. Aspirar con accesorio de tapicería a baja potencia. Manchas: paño seco inmediatamente. Limpieza profesional anual recomendada.',
      origin: 'Taller Noir Atelier · Bogotá, Colombia · Mohair importado de Italia',
      delivery: '8 a 12 semanas',
      stock: 1,
    },
  },
  {
    id: 'sf-luna',      cat: 'sofas', name: 'Luna', coll: 'Maison Doré',
    price: 14200000, w: 260, material: 'Curva escultórica · bouclé', year: 2025,
    spec: {
      desc: 'Sofá de línea curva continua —sin ángulos, sin rupturas— tapizado en bouclé champagne. El respaldo forma un arco suave que envuelve al usuario en una media luna de confort. La estructura interna de acero reforzado mantiene la curva con exactitud milimétrica durante décadas.',
      dims: { largo: 260, profundo: 100, alto: 76, alt_asiento: 42 },
      finish: 'Bouclé champagne · Sin patas visibles — base panel oculto',
      care: 'Aspirar suavemente. Manchas puntuales con paño húmedo y jabón pH neutro. La curva del respaldo no debe cargarse con peso excesivo.',
      origin: 'Taller Luna Design · Bogotá, Colombia',
      delivery: '7 a 10 semanas',
      stock: 2,
    },
  },

  // ── Mesas ──
  {
    id: 'm-orbis',      cat: 'mesas', name: 'Orbis', coll: 'Atelier Noir',
    price: 4200000, w: 110, material: 'Mármol negro Marquina', year: 2025,
    spec: {
      desc: 'Mesa de centro circular en mármol negro Marquina, la piedra calcárea oscura con veteado blanco más icónica de España. El tablero de 3 cm de grosor descansa sobre una base cónica de acero pintado en negro mate, creando un conjunto de presencia gravitacional en cualquier sala.',
      dims: { diam: 110, alto: 38 },
      finish: 'Mármol negro Marquina pulido cara superior · Base acero negro mate',
      care: 'Paño de microfibra seco. Para manchas, agua tibia y jabón pH neutro. Sellar anualmente.',
      origin: 'Canteras Marquina · País Vasco, España · Montaje en taller Bogotá',
      delivery: '6 a 8 semanas',
      stock: 4,
    },
  },
  {
    id: 'm-sole',       cat: 'mesas', name: 'Sole', coll: 'Maison Doré',
    price: 3800000, w: 90, material: 'Latón pulido · vidrio', year: 2024,
    spec: {
      desc: 'Mesa de centro en latón pulido con tablero de vidrio templado de 12mm. La estructura de latón sólido está elaborada en varillas entrelazadas que crean un volumen geométrico luminoso. El latón sin protección lacada desarrolla una pátina orgánica dorada con el tiempo.',
      dims: { diam: 90, alto: 40 },
      finish: 'Latón pulido sin laca — pátina viva · Vidrio templado claro 12mm',
      care: 'Latón: se puede pulir con crema para metales o dejar envejecer naturalmente. Vidrio: limpiacristales sin amoniaco.',
      origin: 'Herrería Dorada · Bogotá, Colombia',
      delivery: '3 a 5 semanas',
      stock: 6,
    },
  },
  {
    id: 'm-pietra',     cat: 'mesas', name: 'Pietra', coll: 'Casa Mediterránea',
    price: 2900000, w: 80, material: 'Travertino · base columna', year: 2024,
    spec: {
      desc: 'Mesa lateral en travertino con base columna de un solo fuste. La sección cónica de la columna y el tablero circular crean una silueta clásica con carácter mediterráneo. El travertino sin pulir en la base contrasta con el acabado pulido del tablero.',
      dims: { diam: 80, alto: 55 },
      finish: 'Tablero travertino pulido · Columna travertino rústico',
      care: 'Sellar anualmente. Limpiar con paño seco o ligeramente húmedo y jabón neutro. Evitar ácidos.',
      origin: 'Canteras Borghese · Roma, Italia · Montaje en taller Bogotá',
      delivery: '5 a 7 semanas',
      stock: 5,
    },
  },
  {
    id: 'm-eclipse',    cat: 'mesas', name: 'Eclipse', coll: 'Atelier Noir',
    price: 5400000, w: 130, material: 'Ónix retroiluminado', year: 2025,
    spec: {
      desc: 'Mesa de centro ovalada en ónix translúcido retroiluminado por LEDs cálidos integrados en la base. En la oscuridad, la mesa emite una luz propia que transforma cualquier sala. La base metálica de perfil bajo está lacada en negro con detalles en latón. Edición limitada: 8 unidades por año.',
      dims: { largo: 130, ancho: 70, alto: 38 },
      finish: 'Ónix miel translúcido pulido · Base acero negro · LEDs integrados 2700K',
      care: 'Ónix: solo paño seco o ligeramente húmedo. Jamás ácidos o abrasivos. Sistema LED: garantía 3 años. Consumo: 12W.',
      origin: 'Taller Piedra & Luz · Ciudad de México, México',
      delivery: '8 a 10 semanas',
      stock: 2,
    },
  },
  {
    id: 'm-rivoli',     cat: 'mesas', name: 'Rivoli', coll: 'Maison Doré',
    price: 3200000, w: 95, material: 'Roble quemado · herraje dorado', year: 2024,
    spec: {
      desc: 'Mesa lateral en roble quemado mediante la técnica japonesa Shou Sugi Ban —carbonización superficial que da al roble un acabado negro ébano con reflejo ligeramente metálico. Las asas y herrajes son de latón pulido 24K. Un contraste radical entre la madera oscurecida y el brillo del metal.',
      dims: { diam: 95, alto: 50 },
      finish: 'Roble quemado Shou Sugi Ban · Herrajes latón pulido 24K',
      care: 'La superficie carbonizada es estable. Limpiar con paño seco. Los herrajes se pulen ocasionalmente con crema para latón.',
      origin: 'Taller Artesano · Bogotá, Colombia',
      delivery: '3 a 5 semanas',
      stock: 4,
    },
  },
  {
    id: 'm-aurora',     cat: 'mesas', name: 'Aurora', coll: 'Maison Doré',
    price: 4700000, w: 120, material: 'Mármol blanco · base latón', year: 2025,
    spec: {
      desc: 'Mesa de centro circular en mármol blanco Bianco Carrara con base trípode en latón laminado. Las tres patas de latón forman un ángulo sofisticado que eleva visualmente el tablero de piedra. Una pieza de delicadeza matemática que domina sin imponerse.',
      dims: { diam: 120, alto: 40 },
      finish: 'Mármol Bianco Carrara pulido · Base latón dorado laminado',
      care: 'Mármol: sellar anualmente, limpiar con paño húmedo y jabón pH neutro. Base latón: puede pulirse o dejarse patiná naturalmente.',
      origin: 'Canteras Carrara · Toscana, Italia · Montaje en taller Bogotá',
      delivery: '6 a 8 semanas',
      stock: 3,
    },
  },

  // ── Lámparas ──
  {
    id: 'l-stella',     cat: 'lamparas', name: 'Stella', coll: 'Maison Doré',
    price: 6800000, material: 'Araña de cristal · 12 luces', year: 2025,
    spec: {
      desc: 'Araña de techo de 12 brazos en latón dorado con prismas de cristal cortado a mano en taller checo. Cada prisma capta y descompone la luz en espectros que animan cualquier techo. Compatible con bombillas E27 de hasta 40W o LED equivalente.',
      dims: { diam: 80, alt_colgante: 65 },
      finish: 'Latón dorado electrodeposición · Cristal cortado a mano en República Checa',
      care: 'Limpiar los prismas con paño de microfibra seco. Para limpieza profunda, desmontar y lavar con agua tibia y jabón suave. Secar completamente antes de reinstalar.',
      origin: 'Cristalería Bohemia · Praga, República Checa · Estructura en taller Bogotá',
      delivery: '8 a 10 semanas',
      stock: 3,
    },
  },
  {
    id: 'l-arc',        cat: 'lamparas', name: 'Arc', coll: 'Atelier Noir',
    price: 4200000, material: 'Mármol y latón · arco escultórico', year: 2024,
    spec: {
      desc: 'Lámpara de pie con base en mármol negro Marquina y arco en latón bruñido de 190cm de altura. La pantalla semiesférica en latón perforado difunde una luz directa hacia abajo con halo lateral decorativo. Un clásico de la iluminación de diseño reinterpretado en materiales de máxima calidad.',
      dims: { base_diam: 30, alt_total: 190, pantalla_diam: 40 },
      finish: 'Base mármol negro pulido · Arco latón bruñido · Pantalla latón perforado',
      care: 'Base mármol: paño seco. Arco y pantalla: paño suave seco o levemente húmedo. Compatible con LED E27 hasta 12W.',
      origin: 'Taller Metálico · Medellín, Colombia · Mármol importado de España',
      delivery: '5 a 7 semanas',
      stock: 4,
    },
  },
  {
    id: 'l-soleil',     cat: 'lamparas', name: 'Soleil', coll: 'Maison Doré',
    price: 3600000, material: 'Disco dorado pulido · LED', year: 2025,
    spec: {
      desc: 'Lámpara de techo tipo disco en latón pulido de 65cm de diámetro con sistema LED integrado de temperatura cálida. El efecto de la luz sobre el latón circular crea un punto focal luminoso que actúa como sol en miniatura. Regulable con atenuador externo.',
      dims: { diam: 65, alt_colgante: 40 },
      finish: 'Latón pulido alto brillo · LEDs integrados 2700K / 2400 lúmenes',
      care: 'Limpiar con paño de microfibra seco o levemente húmedo. El latón puede oscurecerse con el tiempo; pulir con crema para latón para recuperar brillo.',
      origin: 'Taller Iluminación · Bogotá, Colombia',
      delivery: '3 a 5 semanas',
      stock: 6,
    },
  },
  {
    id: 'l-orbita',     cat: 'lamparas', name: 'Órbita', coll: 'Atelier Noir',
    price: 5400000, material: 'Esferas opalinas · estructura latón', year: 2025,
    spec: {
      desc: 'Lámpara de techo compuesta por 8 esferas de cristal opalino blanco en diferentes alturas, suspendidas de una estructura central de latón negro mate. Las esferas, en tres tamaños distintos, crean una constelación colgante que cambia de aspecto según el ángulo de visión.',
      dims: { diam_conjunto: 60, alt_total: 70 },
      finish: 'Estructura latón negro mate · Esferas cristal opalino soplado a mano',
      care: 'Limpiar cada esfera con paño de microfibra seco. Carga máxima: 4W LED por esfera (E14).',
      origin: 'Cristalería Murano · Venecia, Italia · Estructura en taller Bogotá',
      delivery: '7 a 9 semanas',
      stock: 3,
    },
  },
  {
    id: 'l-velo',       cat: 'lamparas', name: 'Velo', coll: 'Casa Mediterránea',
    price: 2400000, material: 'Pantalla seda · base cerámica', year: 2024,
    spec: {
      desc: 'Lámpara de mesa con base en cerámica artesanal en tonos tierra y pantalla en seda natural cruda. La cerámica está torneada a mano en taller mediterráneo y presenta irregularidades propias de la artesanía de autor. La seda filtra la luz convirtiéndola en calidez suave y uniforme.',
      dims: { base_diam: 18, alt_total: 55, pantalla_diam: 30 },
      finish: 'Cerámica vidriada tonos arena · Pantalla seda cruda natural',
      care: 'Base cerámica: paño seco. Pantalla: aspirar suavemente o paño levemente húmedo. No mojar la base eléctrica.',
      origin: 'Taller Cerámica Mediterránea · Valencia, España',
      delivery: '4 a 6 semanas',
      stock: 5,
    },
  },
  {
    id: 'l-noctura',    cat: 'lamparas', name: 'Noctura', coll: 'Atelier Noir',
    price: 1800000, material: 'Sobremesa · ópalo y latón', year: 2025,
    spec: {
      desc: 'Lámpara de sobremesa con cuerpo en cristal ópalo blanco y base en latón negro patinado. El cristal ópalo difunde la luz en 360 grados creando un ambiente nocturno íntimo. Un objeto de iluminación que funciona también como escultura de mesa durante el día.',
      dims: { base_diam: 14, alt_total: 38 },
      finish: 'Cristal ópalo soplado · Base latón negro patinado',
      care: 'Cristal: paño de microfibra seco. Base: paño seco o levemente húmedo. Compatible con LED E14 hasta 6W.',
      origin: 'Taller Cristal · Bogotá, Colombia · Cristal ópalo importado de Italia',
      delivery: '2 a 4 semanas',
      stock: 8,
    },
  },

  // ── Camas ──
  {
    id: 'cm-imperial',  cat: 'camas', name: 'Imperial', coll: 'Atelier Noir',
    price: 14800000, material: 'King size · cabecera capitoné', year: 2025,
    spec: {
      desc: 'Cama king size con cabecera capitoné de 180cm de alto tapizada en cuero negro envejecido. Los botones de capitoné son forjados en latón con grabado artesanal. La base es de roble macizo oscurecido. Incluye dos mesitas de noche a juego. Una pieza que convierte cualquier recámara en suite de gran hotel.',
      dims: { largo_cama: 220, ancho_cama: 200, alt_cabecera: 180 },
      finish: 'Cuero negro envejecido capitoné · Botones latón grabados · Base roble oscurecido',
      care: 'Cuero: hidratante específico cada 3 meses. No exponer a luz solar directa. Base madera: paño seco.',
      origin: 'Taller Tapicería Imperial · Bogotá, Colombia · Cuero importado de Italia',
      delivery: '8 a 12 semanas',
      stock: 2,
    },
  },
  {
    id: 'cm-luxor',     cat: 'camas', name: 'Luxor', coll: 'Maison Doré',
    price: 12200000, material: 'Queen size · marco roble', year: 2024,
    spec: {
      desc: 'Cama queen size con marco de roble americano en acabado natural warm y cabecera tapizada en bouclé marfil. El diseño de la cabecera en tres paneles enmarcados en madera le da carácter arquitectónico. Una pieza equilibrada entre la elegancia y el confort genuino.',
      dims: { largo_cama: 210, ancho_cama: 160, alt_cabecera: 130 },
      finish: 'Marco roble american warm oil · Cabecera bouclé marfil · Cantos madera visibles',
      care: 'Bouclé: aspirar suavemente. Marco roble: paño seco, reacondicionar con aceite de roble anualmente.',
      origin: 'Taller Camas de Autor · Medellín, Colombia',
      delivery: '6 a 8 semanas',
      stock: 3,
    },
  },
  {
    id: 'cm-celeste',   cat: 'camas', name: 'Celeste', coll: 'Maison Doré',
    price: 16900000, material: 'King · cabecera con dosel', year: 2025,
    spec: {
      desc: 'Cama king size con estructura de dosel completo en acero pintado en blanco roto, dotada de una cabecera tapizada en seda dupioni champagne. Cuatro postes de 260cm sostienen el baldaquino opcional. La presencia de esta cama transforma cualquier recámara en un espacio casi teatral.',
      dims: { largo_cama: 220, ancho_cama: 200, alt_postes: 260, alt_cabecera: 150 },
      finish: 'Estructura acero blanco roto mate · Cabecera seda dupioni champagne · Postes forjados',
      care: 'Seda: solo limpieza en seco profesional. Estructura: paño húmedo y secado inmediato. Revisar tensión de tornillos de los postes cada 6 meses.',
      origin: 'Taller Celeste Atelier · Bogotá, Colombia · Seda importada de India',
      delivery: '10 a 14 semanas',
      stock: 1,
    },
  },
  {
    id: 'cm-arena',     cat: 'camas', name: 'Arena', coll: 'Casa Mediterránea',
    price: 8900000, material: 'Queen · lino natural', year: 2024,
    spec: {
      desc: 'Cama queen size con cabecera tapizada en lino natural crudo sin teñir, con estructura de madera de fresno en acabado natural. El diseño minimalista mediterráneo hace de esta cama la compañera perfecta para dormitorios llenos de luz natural.',
      dims: { largo_cama: 210, ancho_cama: 160, alt_cabecera: 110 },
      finish: 'Lino natural crudo · Estructura fresno natural oil finish',
      care: 'Lino: limpiar con paño húmedo y jabón neutro. Airear la cabecera regularmente. Estructura: paño seco.',
      origin: 'Taller Artesano Mediterráneo · Cartagena, Colombia · Lino importado de Bélgica',
      delivery: '4 a 6 semanas',
      stock: 4,
    },
  },

  // ── Sillas ──
  {
    id: 's-bistro',     cat: 'sillas', name: 'Bistro', coll: 'Atelier Noir',
    price: 980000, material: 'Cuero negro · estructura latón', year: 2024,
    spec: {
      desc: 'Silla de comedor con asiento y respaldo en cuero negro genuino y estructura de latón bruñido. La silueta delgada de patas en latón tubo contrasta con la densidad visual del cuero oscuro. Apilable hasta 4 unidades. Precio unitario; disponible en sets de 4 u 8.',
      dims: { ancho: 45, profundo: 50, alto: 88, alt_asiento: 46 },
      finish: 'Cuero negro full-grain · Estructura latón tubo bruñido',
      care: 'Cuero: paño seco y crema hidratante cada 6 meses. Estructura: paño seco o levemente húmedo.',
      origin: 'Taller Mobiliario Fino · Bogotá, Colombia · Cuero colombiano curtido',
      delivery: '3 a 5 semanas (set de 4)',
      stock: 16,
    },
  },
  {
    id: 's-papillon',   cat: 'sillas', name: 'Papillon', coll: 'Maison Doré',
    price: 1240000, material: 'Terciopelo champagne', year: 2025,
    spec: {
      desc: 'Silla de comedor con asiento y respaldo envolvente en terciopelo champagne de pelo corto. La forma del respaldo en media ala —que da nombre a la silla— abraza suavemente la espalda. Las patas doradas forjadas a mano aportan el detalle de joyería que distingue esta silla en cualquier comedor.',
      dims: { ancho: 48, profundo: 52, alto: 90, alt_asiento: 46 },
      finish: 'Terciopelo champagne pelo corto · Patas forjadas en oro mate',
      care: 'Cepillar suavemente en sentido del pelo. No exponer a humedad. Las patas se limpian con paño seco.',
      origin: 'Taller Papillon · Bogotá, Colombia · Terciopelo importado de Italia',
      delivery: '4 a 6 semanas (set de 4)',
      stock: 12,
    },
  },
  {
    id: 's-perla',      cat: 'sillas', name: 'Perla', coll: 'Maison Doré',
    price: 1100000, material: 'Bouclé marfil · pies latón', year: 2025,
    spec: {
      desc: 'Silla de comedor con tapizado completo en bouclé marfil de textura rizada. La forma redondeada sin ángulos agudos le da un carácter amable y contemporáneo. Los pies en latón torneado son el único elemento estructural visible. Un diseño nórdico-parisino.',
      dims: { ancho: 46, profundo: 50, alto: 85, alt_asiento: 45 },
      finish: 'Bouclé marfil · Pies latón torneado',
      care: 'Aspirar suavemente. Manchas: paño húmedo y jabón neutro. Pies: paño seco.',
      origin: 'Taller Perla Design · Bogotá, Colombia · Bouclé importado de Bélgica',
      delivery: '4 a 6 semanas (set de 4)',
      stock: 12,
    },
  },
  {
    id: 's-corte',      cat: 'sillas', name: 'Corte', coll: 'Atelier Noir',
    price: 1480000, material: 'Brazos curvos · cuero cognac', year: 2025,
    spec: {
      desc: 'Silla de comedor con brazos y estructura en madera de nogal oscuro y tapizado en cuero cognac full-aniline. El respaldo con tensión continua en cuero sin costuras visibles es el elemento más técnico de la pieza. Una silla que funciona también como sillón de lectura.',
      dims: { ancho: 58, profundo: 55, alto: 82, alt_asiento: 46 },
      finish: 'Cuero cognac full-aniline · Estructura nogal oscuro barniz mate',
      care: 'Cuero: hidratante específico cada 3 meses. Madera: paño seco. No exponer a luz directa.',
      origin: 'Taller Corte Atelier · Medellín, Colombia · Cuero importado de Italia',
      delivery: '5 a 7 semanas (set de 4)',
      stock: 8,
    },
  },
  {
    id: 's-eden',       cat: 'sillas', name: 'Edén', coll: 'Casa Mediterránea',
    price: 890000, material: 'Ratán natural · cojín lino', year: 2024,
    spec: {
      desc: 'Silla en ratán natural tejido a mano con estructura de madera tropical y cojín de asiento en lino arena removible. La textura orgánica del ratán crea sombras sutiles que cambian con la luz del día. Perfecta para exteriores cubiertos o comedores con clima tropical.',
      dims: { ancho: 50, profundo: 54, alto: 86, alt_asiento: 44 },
      finish: 'Ratán natural tejido · Estructura madera teca · Cojín lino arena',
      care: 'Ratán: limpiar con paño húmedo y cepillo suave. Cojín lino: lavable en lavadora fría. No exponer al sol directo prolongado.',
      origin: 'Taller Artesano · Cartagena, Colombia · Ratán importado de Indonesia',
      delivery: '3 a 5 semanas (set de 4)',
      stock: 16,
    },
  },

  // ── Espejos ──
  {
    id: 'e-luna',       cat: 'espejos', name: 'Luna', coll: 'Maison Doré',
    price: 3400000, material: 'Circular · marco latón martillado', year: 2024,
    spec: {
      desc: 'Espejo circular de 90cm con marco en latón martillado a mano. Cada golpe del martillo crea una superficie irregular que captura y multiplica la luz de forma única. El cristal de espejo es de 4mm, antioxidante, con instalación de colgador oculto incluido.',
      dims: { diam: 90, grosor_marco: 4 },
      finish: 'Marco latón martillado a mano · Espejo plateado 4mm antioxidante',
      care: 'Marco latón: paño seco o crema para latón. Espejo: limpiacristales sin amoniaco con paño de microfibra.',
      origin: 'Herrería Artesanal · Bogotá, Colombia',
      delivery: '3 a 5 semanas',
      stock: 5,
    },
  },
  {
    id: 'e-arche',      cat: 'espejos', name: 'Arche', coll: 'Atelier Noir',
    price: 4200000, material: 'Arco · 220cm · marco bronce', year: 2025,
    spec: {
      desc: 'Espejo de pie en forma de arco ojival de 220cm con marco en bronce envejecido. La forma ojival —inspirada en la arquitectura medieval— le da una presencia arquitectónica que transforma cualquier rincón. El cristal de espejo de 5mm garantiza una reflexión perfecta sin distorsión.',
      dims: { ancho: 80, alto: 220, profundo: 5 },
      finish: 'Marco bronce envejecido · Espejo plateado 5mm sin distorsión',
      care: 'Marco bronce: paño seco. Para mantener el brillo, aplicar crema para metales. Espejo: limpiacristales sin amoniaco.',
      origin: 'Fundición Artesanal · Bogotá, Colombia',
      delivery: '5 a 7 semanas',
      stock: 3,
    },
  },
  {
    id: 'e-fleur',      cat: 'espejos', name: 'Fleur', coll: 'Maison Doré',
    price: 2800000, material: 'Sol radial dorado', year: 2025,
    spec: {
      desc: 'Espejo decorativo circular de 70cm con estructura radial de 32 rayos en latón dorado que irradian desde el centro. El efecto visual de sol o flor hace de este espejo la pieza de mayor impacto decorativo por unidad de precio. Funciona tanto como espejo como objeto de pared.',
      dims: { diam_espejo: 40, diam_total: 90 },
      finish: 'Cristal espejo 4mm · Rayos latón dorado electrodeposición',
      care: 'Espejo: limpiacristales sin amoniaco. Rayos latón: paño seco para mantener el brillo.',
      origin: 'Taller Metales & Espejos · Bogotá, Colombia',
      delivery: '2 a 4 semanas',
      stock: 7,
    },
  },

  // ── Decoración ──
  {
    id: 'd-vaso',       cat: 'decoracion', name: 'Vaso Orbe', coll: 'Maison Doré',
    price: 680000, material: 'Vidrio soplado · acento dorado', year: 2024,
    spec: {
      desc: 'Vasija esférica de vidrio soplado artesanalmente en taller artístico. El acabado interior lleva una capa de hoja de oro 24K que se ve a través del vidrio transparente con efecto nebuloso. Cada pieza es única por la naturaleza del soplado. Precio por pieza talla L (28cm).',
      dims: { diam: 28, alto: 28 },
      finish: 'Vidrio soplado artesanal · Hoja de oro interior 24K',
      care: 'No lavar con agua. Limpiar exterior con paño de microfibra seco. No exponer a luz solar directa prolongada.',
      origin: 'Taller Vidrio de Autor · Bogotá, Colombia',
      delivery: '2 a 3 semanas',
      stock: 12,
    },
  },
  {
    id: 'd-cuadro',     cat: 'decoracion', name: 'Díptico Noir', coll: 'Atelier Noir',
    price: 3200000, material: 'Óleo sobre lino · 2 piezas', year: 2025,
    spec: {
      desc: 'Díptico en óleo sobre lino belga tensado en bastidores de madera, 120 × 80cm cada panel. Composición abstracta en negros, grises y toque de dorado que funciona como unidad o se separa en dos ambientes distintos. Firmada y certificada por el artista. Edición de 6 ejemplares.',
      dims: { ancho_panel: 120, alto_panel: 80, profundo: 4 },
      finish: 'Óleo sobre lino belga · Bastidor madera · Barniz UV protector',
      care: 'No exponer a luz solar directa. Limpiar el marco con paño seco. El barniz UV protege la obra durante décadas.',
      origin: 'Estudio del artista · Bogotá, Colombia · Certificado de autenticidad incluido',
      delivery: '2 a 4 semanas',
      stock: 3,
    },
  },
  {
    id: 'd-escultura',  cat: 'decoracion', name: 'Escultura Torso', coll: 'Atelier Noir',
    price: 2100000, material: 'Bronce patinado', year: 2024,
    spec: {
      desc: 'Escultura de torso femenino abstracto en bronce fundido a la cera perdida con pátina negra. La pieza de 55cm está firmada y numerada por el escultor. La base es de mármol negro pulido. Una obra de arte funcional que convierte cualquier mesa o repisa en un punto focal de alta cultura.',
      dims: { ancho: 22, profundo: 18, alto: 55 },
      finish: 'Bronce fundido patinado negro · Base mármol negro pulido',
      care: 'Bronce: paño seco de algodón. Evitar humedad excesiva. Base mármol: paño húmedo con jabón neutro.',
      origin: 'Fundición de Arte · Bogotá, Colombia · Edición de 12 ejemplares',
      delivery: '3 a 6 semanas',
      stock: 4,
    },
  },
  {
    id: 'd-jarron',     cat: 'decoracion', name: 'Jarrón Atenea', coll: 'Casa Mediterránea',
    price: 540000, material: 'Cerámica artesanal · arena', year: 2024,
    spec: {
      desc: 'Jarrón en cerámica de gres torneado a mano en taller mediterráneo. El acabado en esmalte arena texturado imita la piel de la piedra caliza. La forma balusterada con cuello estrecho y boca abierta es funcional para ramos secos y estética en cualquier superficie.',
      dims: { diam_base: 16, diam_boca: 12, alto: 40 },
      finish: 'Gres esmaltado arena textura piedra · Fondo sellado',
      care: 'Limpiar exterior con paño húmedo. Si se usa para flores, vaciar y secar el interior regularmente. No lavar en lavavajillas.',
      origin: 'Taller Cerámica Artesanal · Cartagena, Colombia',
      delivery: '1 a 3 semanas',
      stock: 18,
    },
  },

  // ── Alfombras ──
  {
    id: 'a-saharah',    cat: 'alfombras', name: 'Saharah', coll: 'Casa Mediterránea',
    price: 4800000, material: 'Lana anudada · 3 × 4 m', year: 2024,
    spec: {
      desc: 'Alfombra de lana anudada a mano en telar vertical por artesanas del norte de Marruecos en técnica bereber. El patrón geométrico abstracto en tonos arena, ocre y blanco roto es único en cada ejemplar por la variación natural del teñido. Densidad de 40.000 nudos por metro cuadrado.',
      dims: { largo: 400, ancho: 300, grosor: 1.2 },
      finish: 'Lana de cordero 100% natural · Teñido con tintes vegetales · Reverso en algodón',
      care: 'Aspirar regularmente sin cepillo rotativo. Manchas: paño húmedo y detergente suave. Limpiar profesionalmente cada 2 años.',
      origin: 'Cooperativa Artesana Bereber · Azilal, Marruecos',
      delivery: '4 a 8 semanas',
      stock: 2,
    },
  },
  {
    id: 'a-onyx',       cat: 'alfombras', name: 'Onyx', coll: 'Atelier Noir',
    price: 6200000, material: 'Seda y lana · grafito', year: 2025,
    spec: {
      desc: 'Alfombra de alto diseño en mezcla de seda y lana, tejida en telar de jacquard con patrón geométrico en tonos grafito, negro mate y plata. El hilo de seda crea reflejos que varían al caminar sobre la alfombra. Una pieza de lujo silencioso: invisible hasta que la luz la revela.',
      dims: { largo: 300, ancho: 200, grosor: 0.8 },
      finish: 'Seda 30% / lana 70% · Reverso antideslizante en algodón',
      care: 'Aspirar en sentido del pelo sin cepillo. Manchas: paño seco de inmediato. Limpieza profesional anual recomendada. No doblar.',
      origin: 'Taller Tejido de Lujo · Nepal · Distribución desde Bogotá',
      delivery: '6 a 8 semanas',
      stock: 3,
    },
  },
  {
    id: 'a-perle',      cat: 'alfombras', name: 'Perle', coll: 'Maison Doré',
    price: 5400000, material: 'Lana marfil con bordes dorados', year: 2025,
    spec: {
      desc: 'Alfombra rectangular en lana pura de alta densidad en tono marfil con bordes terminados a mano en hilo dorado. La superficie con pelo corto uniforme crea una base visual neutra que hace brillar cualquier mueble encima. Los bordes dorados son el único elemento decorativo, con la elegancia de la sobriedad absoluta.',
      dims: { largo: 300, ancho: 200, grosor: 1.0 },
      finish: 'Lana pura marfil pelo corto · Bordes rematados en hilo dorado 24K',
      care: 'Aspirar regularmente. Manchas: paño húmedo y jabón neutro. Los bordes dorados son frágiles; manejar con cuidado al mover.',
      origin: 'Taller Tejido Artístico · Bogotá, Colombia · Lana importada de Nueva Zelanda',
      delivery: '4 a 6 semanas',
      stock: 4,
    },
  },
];

export const KD_ROOMS = [
  {
    id: 'sala', label: 'Sala', area: '38 m²',
    bounds: { x: 2,  y: 4,  w: 50, h: 48 },
    slots: [
      { id: 'sala-sofa',    cat: 'sofas',     label: 'Sofá',          x: 26, y: 16, w: 22, h: 8 },
      { id: 'sala-mesa',    cat: 'mesas',     label: 'Mesa centro',   x: 31, y: 28, w: 12, h: 8 },
      { id: 'sala-lampara', cat: 'lamparas',  label: 'Lámpara',       x: 8,  y: 18, w: 6,  h: 6 },
      { id: 'sala-silla',   cat: 'sillas',    label: 'Sillón',        x: 8,  y: 32, w: 8,  h: 8 },
      { id: 'sala-alfombra',cat: 'alfombras', label: 'Alfombra',      x: 20, y: 14, w: 28, h: 26 },
      { id: 'sala-espejo',  cat: 'espejos',   label: 'Espejo',        x: 47, y: 8,  w: 3,  h: 12 },
    ],
  },
  {
    id: 'comedor', label: 'Comedor', area: '24 m²',
    bounds: { x: 54, y: 4, w: 44, h: 38 },
    slots: [
      { id: 'com-mesa',     cat: 'comedores', label: 'Comedor',       x: 64, y: 12, w: 22, h: 22 },
      { id: 'com-lampara',  cat: 'lamparas',  label: 'Lámpara',       x: 74, y: 8,  w: 4,  h: 4 },
      { id: 'com-deco',     cat: 'decoracion',label: 'Decoración',    x: 92, y: 14, w: 4,  h: 8 },
      { id: 'com-alfombra', cat: 'alfombras', label: 'Alfombra',      x: 60, y: 8,  w: 32, h: 30 },
    ],
  },
  {
    id: 'recamara', label: 'Recámara principal', area: '32 m²',
    bounds: { x: 2, y: 54, w: 50, h: 44 },
    slots: [
      { id: 'rec-cama',     cat: 'camas',     label: 'Cama',          x: 22, y: 64, w: 18, h: 22 },
      { id: 'rec-lampara1', cat: 'lamparas',  label: 'Lámpara',       x: 18, y: 64, w: 3,  h: 3 },
      { id: 'rec-lampara2', cat: 'lamparas',  label: 'Lámpara',       x: 41, y: 64, w: 3,  h: 3 },
      { id: 'rec-espejo',   cat: 'espejos',   label: 'Espejo',        x: 6,  y: 70, w: 3,  h: 12 },
      { id: 'rec-silla',    cat: 'sillas',    label: 'Silla',         x: 6,  y: 88, w: 6,  h: 6 },
      { id: 'rec-alfombra', cat: 'alfombras', label: 'Alfombra',      x: 16, y: 60, w: 30, h: 32 },
    ],
  },
  {
    id: 'recamara2', label: 'Recámara secundaria', area: '20 m²',
    bounds: { x: 54, y: 44, w: 44, h: 54 },
    slots: [
      { id: 'rec2-cama',    cat: 'camas',     label: 'Cama',          x: 60, y: 58, w: 16, h: 20 },
      { id: 'rec2-mesa',    cat: 'mesas',     label: 'Mesa lateral',  x: 78, y: 60, w: 6,  h: 6 },
      { id: 'rec2-lampara', cat: 'lamparas',  label: 'Lámpara',       x: 78, y: 58, w: 3,  h: 3 },
      { id: 'rec2-deco',    cat: 'decoracion',label: 'Cuadro',        x: 92, y: 56, w: 3,  h: 14 },
      { id: 'rec2-alfombra',cat: 'alfombras', label: 'Alfombra',      x: 58, y: 52, w: 32, h: 34 },
    ],
  },
];

export const KD_COLLECTIONS = [
  { id: 'noir', name: 'Atelier Noir',        tagline: 'La sofisticación absoluta del negro',         pieces: 47, year: '2025' },
  { id: 'dore', name: 'Maison Doré',         tagline: 'El esplendor del latón y el champagne',       pieces: 38, year: '2025' },
  { id: 'med',  name: 'Casa Mediterránea',   tagline: 'Travertino, lino y luz del sur',              pieces: 24, year: '2024' },
];

export const KD_TESTIMONIALS = [
  {
    quote: 'Mi sala no parece la misma. Kasa Diamante no vende muebles, vende una manera de habitar el espacio.',
    name: 'Valentina Restrepo',
    role: 'Cliente · Bogotá',
  },
  {
    quote: 'La asesoría fue tan precisa que cada pieza encontró su lugar exacto. Mi casa se siente curada, no decorada.',
    name: 'Andrés Mejía',
    role: 'Arquitecto · Medellín',
  },
  {
    quote: 'El comedor Versalles es el corazón de mis cenas. Los invitados siempre preguntan dónde lo conseguí.',
    name: 'Camila Vélez',
    role: 'Cliente · Cartagena',
  },
];

export const KD_COMBOS = [
  {
    id: 'combo-sala-noir',
    name: 'Sala Atelier Noir',
    room: 'Sala',
    style: 'Atelier Noir',
    tagline: 'Sofisticación absoluta en negro y latón',
    desc: 'El salón más dramático que puedas concebir. Sofá Noir en mohair grafito oscuro, mesa Eclipse en ónix retroiluminado, lámpara Arc de mármol y latón, espejo Arche de 220cm en bronce, alfombra Onyx en seda y lana grafito. Un espacio que convierte cada conversación en un evento memorable.',
    productIds: ['sf-noir', 'm-eclipse', 'l-arc', 'e-arche', 'a-onyx', 'd-escultura'],
    palette: ['#1a1a1a', '#2d2d2d', '#D4AF37', '#808080'],
  },
  {
    id: 'combo-sala-dore',
    name: 'Sala Maison Doré',
    room: 'Sala',
    style: 'Maison Doré',
    tagline: 'Champagne, cristal y mármol blanco',
    desc: 'Sofá Coco en bouclé crema, mesa Aurora en mármol Carrara con trípode de latón, araña Stella de 12 luces en cristal bohemio, espejo Luna en latón martillado, alfombra Perle en lana marfil con bordes dorados. Un salón donde la luz se convierte en protagonista absoluta.',
    productIds: ['sf-coco', 'm-aurora', 'l-stella', 'e-luna', 'a-perle', 'd-vaso'],
    palette: ['#F5F2EA', '#E8C77E', '#D4AF37', '#C8C4B8'],
  },
  {
    id: 'combo-comedor-prestige',
    name: 'Comedor Saint-Honoré',
    room: 'Comedor',
    style: 'Maison Doré',
    tagline: 'Para cenas que se convierten en memoria',
    desc: 'Mesa Saint-Honoré en ónix translúcido retroiluminado, sillas Papillon en terciopelo champagne con patas doradas, araña Stella cayendo desde el techo, espejo Fleur radial dorado en pared lateral. Un comedor que deja sin palabras a cada invitado.',
    productIds: ['c-saint', 's-papillon', 'l-stella', 'd-vaso', 'e-fleur'],
    palette: ['#1a1a1a', '#F5D060', '#F5F2EA', '#D4AF37'],
  },
  {
    id: 'combo-recamara-celeste',
    name: 'Recámara Celeste',
    room: 'Recámara',
    style: 'Maison Doré',
    tagline: 'El retiro privado más sereno',
    desc: 'Cama Celeste king con dosel en acero blanco y seda champagne, mesa Aurora como mesa lateral, lámpara Arc de mármol y latón, espejo Luna en latón martillado, alfombra Perle en lana marfil. Un dormitorio que convierte el descanso en una experiencia de lujo genuino.',
    productIds: ['cm-celeste', 'm-aurora', 'l-arc', 'e-luna', 'a-perle'],
    palette: ['#F9F7F2', '#E8C77E', '#D4AF37', '#C8C4B8'],
  },
  {
    id: 'combo-sala-med',
    name: 'Sala Mediterránea',
    room: 'Sala',
    style: 'Casa Mediterránea',
    tagline: 'Travertino, lino y la luz del sur',
    desc: 'Sofá Ginza en lino belga arena, mesa Pietra en travertino con columna monolítica, lámpara Velo con pantalla de seda y base cerámica, alfombra Saharah bereber anudada a mano, jarrón Atenea en gres. Un espacio que respira, que invita a quedarse sin apresurarse.',
    productIds: ['sf-ginza', 'm-pietra', 'l-velo', 'a-saharah', 'd-jarron'],
    palette: ['#F5F0E8', '#D4C5A9', '#B8A48A', '#8A7560'],
  },
];
